/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'sinyan.lin' at '2015/8/23 上午 9:25' with Gradle 2.6
 *
 * @author sinyan.lin, @date 2015/8/23 上午 9:25
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
