/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'sinyan.lin' at '2015/8/23 上午 9:25' with Gradle 2.6
 *
 * @author sinyan.lin, @date 2015/8/23 上午 9:25
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
